name: Check

on:
  pull_request:
    branches: [ master ]

concurrency:
  group: pr-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
   macos:
     runs-on: macos-latest
     steps:
       - uses: actions/checkout@v3
       - uses: subosito/flutter-action@v2
         with:
           channel: 'stable'
           architecture: x64
           cache: true
       - run: flutter config --enable-macos-desktop
       - run: flutter build macos

   linux:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
       - uses: subosito/flutter-action@v2
         with:
           channel: 'stable'
           cache: true
       - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
       - run: flutter config --enable-linux-desktop
       - run: flutter build linux
   web:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
       - uses: subosito/flutter-action@v2
         with:
           channel: 'stable'
           cache: true
       - run: flutter pub get
       - run: flutter test
       - run: flutter build web

   ios:
      runs-on: macos-latest
      steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          architecture: x64
      - run: flutter pub get
      - run: flutter test
      - run: flutter build ios --release --no-codesign

   android:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
       - uses: actions/setup-java@v2
         with:
           distribution: 'zulu'
           java-version: '11'
           cache: true
       - uses: subosito/flutter-action@v2
         with:
           flutter-version: '3.7.7'
       - run: flutter pub get
       - run: flutter test
       - run: flutter build apk
       - run: flutter build appbundle